Sylius\Component\Taxation\Model\TaxCategory:
    exclusion_policy: ALL
    xml_root_name: tax-category
    properties:
        id:
            expose: true
            type: integer
            xml_attribute: true
            groups: [Default, Detailed]
        name:
            expose: true
            type: string
            groups: [Default, Detailed]
        code:
            expose: true
            type: string
            groups: [Default, Detailed]
        description:
            expose: true
            type: string
            groups: [Detailed]
        createdAt:
            expose: true
            type: DateTime
            groups: [Detailed]
        updatedAt:
            expose: true
            type: DateTime
            groups: [Detailed]
